### ISSUE TITLE
The Minimum Fraction for Tags slider? What kind of fraction is this?

### ISSUE THREAD

**Issue by Thedougler** [picobyte/stable-diffusion-webui-wd14-tagger#22]
So maybe im being dense but its not clear what function the "Minimum Value for Tags: field does

**Comment by picobyte** [comment]
It's a valid question and as your title, fraction, not value (as in your text).

In a batch query, if you have 10 images and 3 images gave 'black hair' as tag, above other thresholds, then setting a fraction of 0.2 will retain 'black hair' whereas a fraction of 0.33 won't (because 3 in 10 is 0.30 which is less than 0.33). Note that you can combine interrogations (checkbox) and then this `minimum fraction' will filter across all the interrogations of the images in your batch,
The minimum fraction can also apply for a single image, with these combined interrogations; if you used 5 different kinds of interrogators, and two yielded 'black hair' that's a fraction of 0.4.

Hope that makes sense.

**Comment by Thedougler** [comment]
Ahh so it's like a "Percent required for positive results"

**Comment by picobyte** [comment]
Yes, except percent is a fraction * 100. My rationale for adding this slider was: oftentimes people use this extension to train for particular features and have collected images with these features, that consequently are very common in their batch of images. This slider makes it easier to select exactly those features that are common in the set.
