### ISSUE TITLE
"'WaifuDiffusionInterrogator' object has no attribute 'postprocess_tags'" 

### ISSUE THREAD

**Issue by Ezil15** [picobyte/stable-diffusion-webui-wd14-tagger#7]
If you try to make an API request, the following response occurs

**{
  "error": "AttributeError",
  "detail": "",
  "body": "",
  "errors": "'WaifuDiffusionInterrogator' object has no attribute 'postprocess_tags'"
}**

It seemsthat the **Interrogate** class has lost the necessary **postprocess_tags** method. If you copy it completely from the original repository, then everything starts working.

**Comment by picobyte** [comment]
The postprocessing of tags code is moved to the QData.apply_filters(), but I fear there are going to be more changes that just this. What is this external api, what is it used for and how is it used?

**Comment by picobyte** [comment]
I've applied a patch ad28db34e0ec9def28b673a0d339fdff09f34396, does that fix this issue?

**Comment by picobyte** [comment]
I've closed this issue, in lack of response, the commit should have fixed it, but you can let me know if it did not.

**Comment by Ezil15** [comment]
Thank you for the quick response to the problem and I apologize for the late response. I am testing the api through the functionality built into the WEB Ui. At the bottom of the page there is an "API" button that allows you to check how various endpoints APIs work.

**Comment by picobyte** [comment]
No problem, Is the issue resolved with the two commits, or is it still dysfunctional? Then I'll reopen

**Comment by picobyte** [comment]
The interrogators does function still, note that the interrogator names have changed. For me the response is
```
{
  "models": [
    "wd14-vit.v1",
    "wd14-vit.v2",
    "wd14-convnext.v1",
    "wd14-convnext.v2",
    "wd14-convnextv2.v1",
    "wd14-swinv2-v1",
    "mld-caformer.dec-5-97527",
    "mld-tresnetd.6-30000",
    "wd-v1-4-moat-tagger.v2",
    "deepdanbooru-v3-20211112-sgd-e28",
    "deepdanbooru-v4-20200814-sgd-e30",
    "wd-v1-4-convnextv2-tagger-v2",
    "Z3D-E621-Convnext"
  ]
}
```
but two were installed manually and may not appear in your list.

The interrogation does give a problem indeed. The query:
```json
{
  "image": "https://upload.wikimedia.org/wikipedia/commons/4/43/Minimalist_info_Icon.png",
  "model": "wd14-vit.v1",
  "threshold": 0.35
}
```
gives a response:
```
{
  "error": "HTTPException",
  "detail": "Invalid encoded image",
  "body": "",
  "errors": ""
}
```

but this error seems to come from the `from modules.api.api import decode_base64_to_image`
and I'm wondering whether this image should be a base64 encoded image that is entered in the string, rather than a link or path

let's try it out [here](https://www.base64-image.de/)

That works just fine.

So, an url does not work? Also the threhold, I don't believe this does anything, currently. I believe there could be some more options.
